wheels pyproject: add python 3.14 (remove 3.11), build mac arm64 on github

diff --git a/.github/workflows/wheels.yml b/.github/workflows/wheels.yml
--- a/.github/workflows/wheels.yml
+++ b/.github/workflows/wheels.yml
@@ -43,6 +43,18 @@ jobs:
         os: [ubuntu-latest, macos-latest, windows-latest]
 
     steps:
+
+    # builds on x86_64 failed to produce arm64 wheels a few years ago. Ensure macOS runners are arm64.
+    - name: macOS ensure arm64
+      if: runner.os == 'macOS'
+      run: |
+        echo "macOS architecture:"
+        uname -m
+        if [ "$(uname -m)" != "arm64" ]; then
+        echo "This runner is not arm64 architecture. Failing the build."
+        exit 1
+        fi
+
     - uses: actions/checkout@v6
       with:
         submodules: recursive
